import { DEMO_ADDRESS } from '@/lib/template-demo'
import {
  TEMPLATE_PRESETS,
  type RestaurantTemplateSlug,
  type TemplatePreset,
} from '@/lib/restaurant-customization'
import type { Template } from '@/types/template'

export interface TemplateSampleProduct {
  nome: string
  descricao: string
  preco: number
  categoria: string
  ordem: number
  imagem_url?: string
}

type TemplateIconKey =
  | 'store'
  | 'pizza'
  | 'burger'
  | 'beer'
  | 'coffee'
  | 'ice-cream'
  | 'fish'

export interface RestaurantTemplateConfig {
  slug: RestaurantTemplateSlug
  iconKey: TemplateIconKey
  name: string
  shortDescription: string
  description: string
  category: Template['category']
  imageUrl: string
  previewUrl: string
  /** Preço mensal em R$ */
  priceMonthly: number
  /** Preço anual em R$ (desconto = 2 meses grátis) */
  priceAnnual: number
  price: number
  originalPrice: number
  isFeatured: boolean
  isNew: boolean
  isBestseller: boolean
  salesCount: number
  ratingAvg: number
  ratingCount: number
  eyebrow: string
  accent: string
  chip: string
  highlights: string[]
  features: string[]
  slogan: string
  cor_primaria: string
  cor_secundaria: string
  preset: TemplatePreset
  sampleProducts: TemplateSampleProduct[]
}

export const RESTAURANT_TEMPLATE_CONFIGS: Record<RestaurantTemplateSlug, RestaurantTemplateConfig> = {
  restaurante: {
    slug: 'restaurante',
    iconKey: 'store',
    name: 'Restaurante / Marmitaria',
    shortDescription: 'Para restaurantes e marmitarias',
    description:
      'Cardápio ideal para restaurantes, marmitarias e self-service. Organizado por pratos executivos, porções e bebidas.',
    category: 'restaurante',
    imageUrl:
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=900&auto=format&fit=crop&q=80',
    previewUrl: '/templates/restaurante',
    priceMonthly: 59,
    priceAnnual: 590,
    price: 59,
    originalPrice: 708,
    isFeatured: true,
    isNew: false,
    isBestseller: true,
    salesCount: 156,
    ratingAvg: 4.8,
    ratingCount: 42,
    eyebrow: 'Operação de almoço',
    accent: 'from-amber-500/25 via-orange-500/15 to-transparent',
    chip: 'bg-amber-500/15 text-amber-800',
    highlights: ['Pratos do dia', 'Marmitas', 'Combos executivos'],
    features: ['Pratos executivos', 'Marmitas', 'Porções', 'Bebidas', 'Sobremesas'],
    slogan: 'Pratos do dia, combos e delivery em um só lugar.',
    cor_primaria: '#d97706',
    cor_secundaria: '#ea580c',
    preset: TEMPLATE_PRESETS.restaurante,
    sampleProducts: [
      {
        nome: 'Prato Executivo da Casa',
        descricao: 'Arroz, feijão, proteína do dia, salada e acompanhamento.',
        preco: 29.9,
        categoria: 'Pratos executivos',
        ordem: 1,
      },
      {
        nome: 'Filé de Frango Grelhado',
        descricao: 'Arroz, feijão, filé de frango grelhado, salada e batata.',
        preco: 32.9,
        categoria: 'Pratos executivos',
        ordem: 2,
      },
      {
        nome: 'Carne Moída com Purê',
        descricao: 'Arroz, feijão, carne moída temperada, purê de batata e salada.',
        preco: 30.9,
        categoria: 'Pratos executivos',
        ordem: 3,
      },
      {
        nome: 'Bife Acebolado',
        descricao: 'Arroz, feijão, bife grelhado com cebola e batata frita.',
        preco: 33.9,
        categoria: 'Pratos executivos',
        ordem: 4,
      },
      {
        nome: 'Omelete',
        descricao: 'Omelete com queijo e presunto, arroz e salada.',
        preco: 28.9,
        categoria: 'Pratos executivos',
        ordem: 5,
      },
      {
        nome: 'Filé de Peixe',
        descricao: 'Arroz, legumes, filé de tilápia grelhado e salada.',
        preco: 36.9,
        categoria: 'Pratos executivos',
        ordem: 6,
      },
      {
        nome: 'Marmita Tradicional',
        descricao: 'Arroz, feijão, carne, salada e dois acompanhamentos.',
        preco: 28.9,
        categoria: 'Marmitas',
        ordem: 7,
      },
      {
        nome: 'Marmita Fitness',
        descricao: 'Arroz integral, frango grelhado, legumes no vapor e salada.',
        preco: 34.9,
        categoria: 'Marmitas',
        ordem: 8,
      },
      {
        nome: 'Marmita Família',
        descricao: 'Porção para 4 pessoas. Arroz, feijão, 2 proteínas e acompanhamentos.',
        preco: 89.9,
        categoria: 'Marmitas',
        ordem: 9,
      },
      {
        nome: 'Marmita Low Carb',
        descricao: 'Couve-flor, brócolis, frango grelhado e salada.',
        preco: 36.9,
        categoria: 'Marmitas',
        ordem: 10,
      },
      {
        nome: 'Porção de Batata Frita',
        descricao: 'Batata frita crocante, serve 2 pessoas.',
        preco: 18.9,
        categoria: 'Acompanhamentos',
        ordem: 10,
      },
      {
        nome: 'Salada Verde',
        descricao: 'Alface, tomate, cebola e molho à escolha.',
        preco: 12.9,
        categoria: 'Acompanhamentos',
        ordem: 11,
      },
      {
        nome: 'Arroz com Ovo',
        descricao: 'Arroz soltinho com ovo frito ou mexido.',
        preco: 10.9,
        categoria: 'Acompanhamentos',
        ordem: 12,
      },
      {
        nome: 'Farofa',
        descricao: 'Farofa de bacon ou tradicional.',
        preco: 8.9,
        categoria: 'Acompanhamentos',
        ordem: 13,
      },
      {
        nome: 'Polenta Frita',
        descricao: 'Porção de polenta frita crocante.',
        preco: 12.9,
        categoria: 'Acompanhamentos',
        ordem: 14,
      },
      {
        nome: 'Pudim de Leite',
        descricao: 'Fatia individual com calda de caramelo.',
        preco: 9.9,
        categoria: 'Sobremesas',
        ordem: 15,
      },
      {
        nome: 'Bolo Caseiro',
        descricao: 'Fatia de bolo do dia. Sabores variados.',
        preco: 8.9,
        categoria: 'Sobremesas',
        ordem: 16,
      },
      {
        nome: 'Gelatina',
        descricao: 'Gelatina sabor morango, uva ou abacaxi.',
        preco: 6.9,
        categoria: 'Sobremesas',
        ordem: 17,
      },
      {
        nome: 'Sorvete',
        descricao: 'Bola de sorvete. Sabores variados.',
        preco: 8.9,
        categoria: 'Sobremesas',
        ordem: 18,
      },
      {
        nome: 'Mousse de Maracujá',
        descricao: 'Mousse cremosa de maracujá.',
        preco: 9.9,
        categoria: 'Sobremesas',
        ordem: 19,
      },
      {
        nome: 'Suco Natural 500ml',
        descricao: 'Laranja, limão ou abacaxi com hortelã.',
        preco: 8.9,
        categoria: 'Bebidas',
        ordem: 20,
      },
      {
        nome: 'Refrigerante 2L',
        descricao: 'Coca-Cola, Guaraná ou Fanta.',
        preco: 12.9,
        categoria: 'Bebidas',
        ordem: 21,
      },
      {
        nome: 'Água Mineral 500ml',
        descricao: 'Água mineral sem gás.',
        preco: 4.9,
        categoria: 'Bebidas',
        ordem: 22,
      },
      {
        nome: 'Café',
        descricao: 'Café coado ou expresso.',
        preco: 4.9,
        categoria: 'Bebidas',
        ordem: 23,
      },
      {
        nome: 'Suco de Laranja 1L',
        descricao: 'Suco natural de laranja.',
        preco: 14.9,
        categoria: 'Bebidas',
        ordem: 24,
      },
    ],
  },
  pizzaria: {
    slug: 'pizzaria',
    iconKey: 'pizza',
    name: 'Pizzaria',
    shortDescription: 'Para pizzarias',
    description:
      'Cardápio completo para pizzarias com opções de tamanhos, sabores e bordas recheadas.',
    category: 'pizzaria',
    imageUrl:
      'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=900&auto=format&fit=crop&q=80',
    previewUrl: '/templates/pizzaria',
    priceMonthly: 69,
    priceAnnual: 690,
    price: 69,
    originalPrice: 828,
    isFeatured: true,
    isNew: false,
    isBestseller: false,
    salesCount: 89,
    ratingAvg: 4.7,
    ratingCount: 28,
    eyebrow: 'Ticket alto no delivery',
    accent: 'from-red-600/25 via-red-500/15 to-orange-500/10',
    chip: 'bg-red-500/15 text-red-800',
    highlights: ['Sabores e bordas', 'Combos família', 'Upsell de bebida'],
    features: ['Pizzas tradicionais', 'Pizzas especiais', 'Bordas recheadas', 'Bebidas', 'Combos'],
    slogan: 'Sabores, combos e bordas com pedido rápido.',
    cor_primaria: '#dc2626',
    cor_secundaria: '#ea580c',
    preset: TEMPLATE_PRESETS.pizzaria,
    sampleProducts: [
      {
        nome: 'Calabresa',
        descricao: 'Molho de tomate, mussarela, calabresa fatiada e cebola',
        preco: 45.9,
        categoria: 'Pizzas Tradicionais',
        ordem: 1,
      },
      {
        nome: 'Mussarela',
        descricao: 'Molho de tomate, mussarela e orégano',
        preco: 42.9,
        categoria: 'Pizzas Tradicionais',
        ordem: 2,
      },
      {
        nome: 'Portuguesa',
        descricao: 'Molho de tomate, mussarela, presunto, ovos, cebola e azeitona',
        preco: 49.9,
        categoria: 'Pizzas Tradicionais',
        ordem: 3,
      },
      {
        nome: 'Frango com Catupiry',
        descricao: 'Molho de tomate, mussarela, frango desfiado e catupiry',
        preco: 52.9,
        categoria: 'Pizzas Tradicionais',
        ordem: 4,
      },
      {
        nome: 'Napolitana',
        descricao: 'Molho de tomate, mussarela, tomate e orégano',
        preco: 44.9,
        categoria: 'Pizzas Tradicionais',
        ordem: 5,
      },
      {
        nome: 'Atum',
        descricao: 'Molho de tomate, mussarela, atum e cebola',
        preco: 49.9,
        categoria: 'Pizzas Tradicionais',
        ordem: 6,
      },
      {
        nome: 'Bacon',
        descricao: 'Molho de tomate, mussarela e bacon crocante',
        preco: 51.9,
        categoria: 'Pizzas Tradicionais',
        ordem: 7,
      },
      {
        nome: 'Milho',
        descricao: 'Molho de tomate, mussarela e milho verde',
        preco: 43.9,
        categoria: 'Pizzas Tradicionais',
        ordem: 8,
      },
      {
        nome: 'Palmito',
        descricao: 'Molho de tomate, mussarela e palmito',
        preco: 48.9,
        categoria: 'Pizzas Tradicionais',
        ordem: 9,
      },
      {
        nome: 'Escarola',
        descricao: 'Molho de tomate, mussarela, escarola e azeitona',
        preco: 46.9,
        categoria: 'Pizzas Tradicionais',
        ordem: 10,
      },
      {
        nome: 'Aliche',
        descricao: 'Molho de tomate, mussarela e aliche importado',
        preco: 54.9,
        categoria: 'Pizzas Tradicionais',
        ordem: 11,
      },
      {
        nome: 'Quatro Queijos',
        descricao: 'Mussarela, provolone, gorgonzola e parmesão',
        preco: 58.9,
        categoria: 'Pizzas Especiais',
        ordem: 12,
      },
      {
        nome: 'Pepperoni',
        descricao: 'Molho de tomate, mussarela e pepperoni importado',
        preco: 56.9,
        categoria: 'Pizzas Especiais',
        ordem: 13,
      },
      {
        nome: 'Margherita',
        descricao: 'Molho de tomate, mussarela de búfala, tomate e manjericão fresco',
        preco: 54.9,
        categoria: 'Pizzas Especiais',
        ordem: 14,
      },
      {
        nome: 'Strogonoff',
        descricao: 'Strogonoff de carne ou frango, batata palha e mussarela',
        preco: 59.9,
        categoria: 'Pizzas Especiais',
        ordem: 15,
      },
      {
        nome: 'Canadense',
        descricao: 'Molho de tomate, mussarela, presunto, bacon e champignon',
        preco: 56.9,
        categoria: 'Pizzas Especiais',
        ordem: 16,
      },
      {
        nome: 'Cheddar com Bacon',
        descricao: 'Molho de tomate, cheddar cremoso e bacon',
        preco: 57.9,
        categoria: 'Pizzas Especiais',
        ordem: 17,
      },
      {
        nome: 'Bacon com Cheddar',
        descricao: 'Mussarela, bacon crocante e cheddar derretido',
        preco: 55.9,
        categoria: 'Pizzas Especiais',
        ordem: 18,
      },
      {
        nome: 'Chocolate com Morango',
        descricao: 'Chocolate ao leite, morangos frescos e leite condensado',
        preco: 48.9,
        categoria: 'Pizzas Doces',
        ordem: 19,
      },
      {
        nome: 'Romeu e Julieta',
        descricao: 'Mussarela e goiabada cremosa',
        preco: 44.9,
        categoria: 'Pizzas Doces',
        ordem: 20,
      },
      {
        nome: 'Banana com Canela',
        descricao: 'Banana, canela e açúcar. Sobremesa em forma de pizza.',
        preco: 42.9,
        categoria: 'Pizzas Doces',
        ordem: 21,
      },
      {
        nome: 'Chocolate Branco',
        descricao: 'Chocolate branco e morango.',
        preco: 46.9,
        categoria: 'Pizzas Doces',
        ordem: 22,
      },
      {
        nome: 'Prestígio',
        descricao: 'Chocolate e coco ralado.',
        preco: 47.9,
        categoria: 'Pizzas Doces',
        ordem: 23,
      },
      {
        nome: 'Borda de Catupiry',
        descricao: 'Adicional para qualquer pizza',
        preco: 8,
        categoria: 'Bordas Recheadas',
        ordem: 24,
      },
      {
        nome: 'Borda de Cheddar',
        descricao: 'Adicional para qualquer pizza',
        preco: 8,
        categoria: 'Bordas Recheadas',
        ordem: 25,
      },
      {
        nome: 'Borda de Bacon',
        descricao: 'Adicional para qualquer pizza',
        preco: 9,
        categoria: 'Bordas Recheadas',
        ordem: 26,
      },
      {
        nome: 'Borda de Chocolate',
        descricao: 'Adicional para pizzas doces',
        preco: 10,
        categoria: 'Bordas Recheadas',
        ordem: 27,
      },
      {
        nome: 'Refrigerante 2L',
        descricao: 'Coca-Cola, Guaraná ou Fanta',
        preco: 14,
        categoria: 'Bebidas',
        ordem: 28,
      },
      {
        nome: 'Suco Natural 1L',
        descricao: 'Laranja, limão ou maracujá',
        preco: 16,
        categoria: 'Bebidas',
        ordem: 29,
      },
      {
        nome: 'Água Mineral 1,5L',
        descricao: 'Água mineral sem gás.',
        preco: 6,
        categoria: 'Bebidas',
        ordem: 30,
      },
      {
        nome: 'Refrigerante 350ml',
        descricao: 'Coca-Cola, Guaraná ou Fanta.',
        preco: 6,
        categoria: 'Bebidas',
        ordem: 31,
      },
      {
        nome: 'Suco de Laranja 500ml',
        descricao: 'Suco natural de laranja.',
        preco: 10,
        categoria: 'Bebidas',
        ordem: 32,
      },
      {
        nome: 'Cerveja 350ml',
        descricao: 'Heineken, Brahma ou Stella.',
        preco: 8,
        categoria: 'Bebidas',
        ordem: 33,
      },
      {
        nome: 'Combo Pizza Média + Refri 2L',
        descricao: 'Pizza média à escolha + refrigerante 2L.',
        preco: 54.9,
        categoria: 'Combos',
        ordem: 34,
      },
      {
        nome: 'Combo 2 Pizzas Médias',
        descricao: 'Duas pizzas médias à escolha. Ideal para compartilhar.',
        preco: 89.9,
        categoria: 'Combos',
        ordem: 35,
      },
      {
        nome: 'Combo Família',
        descricao: 'Pizza grande + 2 refrigerantes 2L + batata frita.',
        preco: 99.9,
        categoria: 'Combos',
        ordem: 36,
      },
      {
        nome: 'Combo Broto + Refri',
        descricao: 'Pizza broto à escolha + refrigerante 350ml.',
        preco: 34.9,
        categoria: 'Combos',
        ordem: 37,
      },
      {
        nome: 'Combo Meio a Meio',
        descricao: 'Pizza média com dois sabores + refrigerante 2L.',
        preco: 62.9,
        categoria: 'Combos',
        ordem: 38,
      },
    ],
  },
  lanchonete: {
    slug: 'lanchonete',
    iconKey: 'burger',
    name: 'Hamburgueria / Lanchonete',
    shortDescription: 'Para lanchonetes e hamburguerias',
    description:
      'Cardápio para lanchonetes e hamburguerias artesanais. Com adicionais e combos personalizados.',
    category: 'lanchonete',
    imageUrl:
      'https://images.unsplash.com/photo-1550547660-d9450f859349?w=900&auto=format&fit=crop&q=80',
    previewUrl: '/templates/lanchonete',
    priceMonthly: 57,
    priceAnnual: 570,
    price: 57,
    originalPrice: 684,
    isFeatured: false,
    isNew: true,
    isBestseller: false,
    salesCount: 67,
    ratingAvg: 4.9,
    ratingCount: 19,
    eyebrow: 'Montagem e adicionais',
    accent: 'from-amber-400/25 via-yellow-500/15 to-orange-500/10',
    chip: 'bg-amber-400/20 text-amber-900',
    highlights: ['Combos prontos', 'Adicionais', 'Cards agressivos'],
    features: ['Hambúrgueres', 'Hot dogs', 'Porções', 'Bebidas', 'Combos'],
    slogan: 'Lanches e combos com visual que abre o apetite.',
    cor_primaria: '#eab308',
    cor_secundaria: '#f97316',
    preset: TEMPLATE_PRESETS.lanchonete,
    sampleProducts: [
      {
        nome: 'X-Burguer',
        descricao: 'Pão, hambúrguer bovino, queijo, alface e tomate.',
        preco: 22.9,
        categoria: 'Hambúrgueres',
        ordem: 1,
      },
      {
        nome: 'X-Salada',
        descricao: 'Pão, hambúrguer, queijo, alface, tomate e maionese.',
        preco: 24.9,
        categoria: 'Hambúrgueres',
        ordem: 2,
      },
      {
        nome: 'Burger Artesanal',
        descricao: 'Pão brioche, burger bovino 180g, cheddar e bacon crocante.',
        preco: 32.9,
        categoria: 'Hambúrgueres',
        ordem: 3,
      },
      {
        nome: 'X-Frango',
        descricao: 'Pão, filé de frango empanado, queijo, alface e tomate.',
        preco: 26.9,
        categoria: 'Hambúrgueres',
        ordem: 4,
      },
      {
        nome: 'X-Bacon',
        descricao: 'Pão, hambúrguer, queijo, bacon crocante, alface e tomate.',
        preco: 28.9,
        categoria: 'Hambúrgueres',
        ordem: 5,
      },
      {
        nome: 'X-Tudo',
        descricao: 'Pão, hambúrguer, queijo, presunto, bacon, ovo, alface e tomate.',
        preco: 32.9,
        categoria: 'Hambúrgueres',
        ordem: 6,
      },
      {
        nome: 'X-Egg',
        descricao: 'Pão, hambúrguer, queijo, ovo frito, alface e tomate.',
        preco: 26.9,
        categoria: 'Hambúrgueres',
        ordem: 7,
      },
      {
        nome: 'X-Calabresa',
        descricao: 'Pão, hambúrguer, queijo, calabresa fatiada e cebola.',
        preco: 27.9,
        categoria: 'Hambúrgueres',
        ordem: 8,
      },
      {
        nome: 'Smash Burger',
        descricao: 'Dois smash burgers, queijo cheddar e molho especial.',
        preco: 34.9,
        categoria: 'Hambúrgueres',
        ordem: 9,
      },
      {
        nome: 'Hot Dog Tradicional',
        descricao: 'Pão, salsicha, purê, batata palha, milho e molhos.',
        preco: 18.9,
        categoria: 'Hot Dogs',
        ordem: 10,
      },
      {
        nome: 'Hot Dog Completo',
        descricao: 'Pão, 2 salsichas, purê, batata palha, milho, ovo e molhos.',
        preco: 22.9,
        categoria: 'Hot Dogs',
        ordem: 11,
      },
      {
        nome: 'Hot Dog Premium',
        descricao: 'Pão especial, salsicha premium, bacon, cheddar e molho especial.',
        preco: 26.9,
        categoria: 'Hot Dogs',
        ordem: 12,
      },
      {
        nome: 'Batata Frita',
        descricao: 'Porção individual de batata frita crocante.',
        preco: 14.9,
        categoria: 'Acompanhamentos',
        ordem: 13,
      },
      {
        nome: 'Batata com Cheddar e Bacon',
        descricao: 'Batata frita com cheddar derretido e bacon crocante.',
        preco: 21.9,
        categoria: 'Acompanhamentos',
        ordem: 14,
      },
      {
        nome: 'Anel de Cebola',
        descricao: '6 unidades empanadas e fritas.',
        preco: 16.9,
        categoria: 'Acompanhamentos',
        ordem: 15,
      },
      {
        nome: 'Nuggets',
        descricao: '8 unidades de nuggets crocantes com molho.',
        preco: 18.9,
        categoria: 'Acompanhamentos',
        ordem: 16,
      },
      {
        nome: 'Onion Rings',
        descricao: 'Porção de anéis de cebola empanados.',
        preco: 17.9,
        categoria: 'Acompanhamentos',
        ordem: 17,
      },
      {
        nome: 'Combo X-Salada + Batata + Refri',
        descricao: 'X-Salada, batata média e refrigerante 350ml.',
        preco: 34.9,
        categoria: 'Combos',
        ordem: 18,
      },
      {
        nome: 'Combo Duplo + Fritas + 2 Refris',
        descricao: '2 X-Burguer, batata grande e 2 refrigerantes.',
        preco: 49.9,
        categoria: 'Combos',
        ordem: 19,
      },
      {
        nome: 'Combo Família',
        descricao: '4 X-Burguer, 2 batatas grandes e 4 refrigerantes.',
        preco: 89.9,
        categoria: 'Combos',
        ordem: 20,
      },
      {
        nome: 'Combo X-Tudo + Batata',
        descricao: 'X-Tudo, batata média e refrigerante 350ml.',
        preco: 42.9,
        categoria: 'Combos',
        ordem: 21,
      },
      {
        nome: 'Combo Smash + Fritas',
        descricao: 'Smash Burger, batata com cheddar e refrigerante.',
        preco: 44.9,
        categoria: 'Combos',
        ordem: 22,
      },
      {
        nome: 'Refrigerante 350ml',
        descricao: 'Coca-Cola, Guaraná ou Fanta.',
        preco: 5.9,
        categoria: 'Bebidas',
        ordem: 23,
      },
      {
        nome: 'Refrigerante 2L',
        descricao: 'Coca-Cola, Guaraná ou Fanta.',
        preco: 12.9,
        categoria: 'Bebidas',
        ordem: 24,
      },
      {
        nome: 'Suco Natural 500ml',
        descricao: 'Laranja, limão, maracujá ou abacaxi.',
        preco: 10.9,
        categoria: 'Bebidas',
        ordem: 25,
      },
      {
        nome: 'Água Mineral 500ml',
        descricao: 'Água mineral sem gás.',
        preco: 4.9,
        categoria: 'Bebidas',
        ordem: 26,
      },
      {
        nome: 'Milk Shake',
        descricao: 'Chocolate, morango ou baunilha.',
        preco: 16.9,
        categoria: 'Bebidas',
        ordem: 27,
      },
    ],
  },
  bar: {
    slug: 'bar',
    iconKey: 'beer',
    name: 'Bar / Pub',
    shortDescription: 'Para bares e pubs',
    description:
      'Cardápio para bares, pubs e casas noturnas. Com drinks, cervejas artesanais e petiscos.',
    category: 'bar',
    imageUrl:
      'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=900&auto=format&fit=crop&q=80',
    previewUrl: '/templates/bar',
    priceMonthly: 64,
    priceAnnual: 640,
    price: 64,
    originalPrice: 768,
    isFeatured: false,
    isNew: false,
    isBestseller: false,
    salesCount: 34,
    ratingAvg: 4.6,
    ratingCount: 12,
    eyebrow: 'Noite e giro rápido',
    accent: 'from-zinc-800/40 via-amber-900/20 to-zinc-900/30',
    chip: 'bg-amber-900/30 text-amber-200',
    highlights: ['Happy hour', 'Drinks', 'Petiscos'],
    features: ['Cervejas', 'Drinks', 'Porções', 'Sem álcool', 'Happy hour'],
    slogan: 'Petiscos e drinks organizados para vender mais.',
    cor_primaria: '#78350f',
    cor_secundaria: '#b45309',
    preset: TEMPLATE_PRESETS.bar,
    sampleProducts: [
      {
        nome: 'Porção de Batata Frita',
        descricao: 'Batata frita crocante com molho especial. Serve 2.',
        preco: 28.9,
        categoria: 'Petiscos',
        ordem: 1,
      },
      {
        nome: 'Frango à Passarinha',
        descricao: 'Coxas e sobrecoxas crocantes. Serve 2 pessoas.',
        preco: 42.9,
        categoria: 'Petiscos',
        ordem: 2,
      },
      {
        nome: 'Tábua de Frios',
        descricao: 'Queijos, presunto, salame e azeitonas. Serve 3.',
        preco: 54.9,
        categoria: 'Petiscos',
        ordem: 3,
      },
      {
        nome: 'Bolinho de Bacalhau',
        descricao: '6 unidades com molho tártaro.',
        preco: 32.9,
        categoria: 'Petiscos',
        ordem: 4,
      },
      {
        nome: 'Camarão à Milanesa',
        descricao: '8 unidades empanadas com molho especial.',
        preco: 48.9,
        categoria: 'Petiscos',
        ordem: 5,
      },
      {
        nome: 'Coxinha',
        descricao: '4 unidades de coxinha de frango.',
        preco: 22.9,
        categoria: 'Petiscos',
        ordem: 6,
      },
      {
        nome: 'Pastel de Queijo',
        descricao: '4 unidades de pastel frito.',
        preco: 18.9,
        categoria: 'Petiscos',
        ordem: 7,
      },
      {
        nome: 'Mandioca Frita',
        descricao: 'Porção de mandioca frita crocante.',
        preco: 24.9,
        categoria: 'Petiscos',
        ordem: 8,
      },
      {
        nome: 'Isca de Peixe',
        descricao: 'Iscas de tilápia empanadas com molho tártaro.',
        preco: 38.9,
        categoria: 'Petiscos',
        ordem: 9,
      },
      {
        nome: 'Chopp 300ml',
        descricao: 'Chopp gelado da torneira.',
        preco: 12.9,
        categoria: 'Cervejas',
        ordem: 10,
      },
      {
        nome: 'Chopp 600ml',
        descricao: 'Chopp gelado caneco.',
        preco: 18.9,
        categoria: 'Cervejas',
        ordem: 11,
      },
      {
        nome: 'Long Neck',
        descricao: 'Heineken, Brahma ou Stella Artois.',
        preco: 10.9,
        categoria: 'Cervejas',
        ordem: 12,
      },
      {
        nome: 'Balde 6 Long Necks',
        descricao: 'Seleção gelada para compartilhar.',
        preco: 54.9,
        categoria: 'Cervejas',
        ordem: 13,
      },
      {
        nome: 'Cerveja Artesanal',
        descricao: 'Pilsen, IPA ou Weiss. Consulte disponibilidade.',
        preco: 18.9,
        categoria: 'Cervejas',
        ordem: 14,
      },
      {
        nome: 'Caipirinha',
        descricao: 'Limão, cachaça, açúcar e gelo.',
        preco: 18.9,
        categoria: 'Drinks',
        ordem: 15,
      },
      {
        nome: 'Caipirinha de Frutas',
        descricao: 'Maracujá, morango ou abacaxi.',
        preco: 22.9,
        categoria: 'Drinks',
        ordem: 16,
      },
      {
        nome: 'Gin Tônica',
        descricao: 'Gin, tônica e toque cítrico.',
        preco: 24.9,
        categoria: 'Drinks',
        ordem: 17,
      },
      {
        nome: 'Mojito',
        descricao: 'Rum, hortelã, limão, açúcar e soda.',
        preco: 22.9,
        categoria: 'Drinks',
        ordem: 18,
      },
      {
        nome: 'Sex on the Beach',
        descricao: 'Vodka, licor de pêssego, suco de laranja e cranberry.',
        preco: 26.9,
        categoria: 'Drinks',
        ordem: 19,
      },
      {
        nome: 'Whisky',
        descricao: 'Dose de whisky. Consulte marcas disponíveis.',
        preco: 28.9,
        categoria: 'Drinks',
        ordem: 20,
      },
      {
        nome: 'Vodka com Energético',
        descricao: 'Vodka com Red Bull ou similar.',
        preco: 24.9,
        categoria: 'Drinks',
        ordem: 21,
      },
      {
        nome: 'Refrigerante 350ml',
        descricao: 'Coca-Cola, Guaraná ou água.',
        preco: 6.9,
        categoria: 'Sem álcool',
        ordem: 22,
      },
      {
        nome: 'Suco Natural 500ml',
        descricao: 'Laranja, limão, maracujá ou abacaxi.',
        preco: 12.9,
        categoria: 'Sem álcool',
        ordem: 23,
      },
      {
        nome: 'Água com Gás',
        descricao: 'Água mineral com gás e limão.',
        preco: 8.9,
        categoria: 'Sem álcool',
        ordem: 24,
      },
      {
        nome: 'Água Tônica',
        descricao: 'Água tônica gelada com limão.',
        preco: 8.9,
        categoria: 'Sem álcool',
        ordem: 25,
      },
      {
        nome: 'Suco de Laranja Natural',
        descricao: 'Suco de laranja espremido na hora.',
        preco: 14.9,
        categoria: 'Sem álcool',
        ordem: 26,
      },
    ],
  },
  cafeteria: {
    slug: 'cafeteria',
    iconKey: 'coffee',
    name: 'Cafeteria',
    shortDescription: 'Para cafeterias e padarias',
    description:
      'Cardápio para cafeterias, padarias e confeitarias. Com cafés especiais, doces e salgados.',
    category: 'cafeteria',
    imageUrl:
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=900&auto=format&fit=crop&q=80',
    previewUrl: '/templates/cafeteria',
    priceMonthly: 54,
    priceAnnual: 540,
    price: 54,
    originalPrice: 648,
    isFeatured: false,
    isNew: true,
    isBestseller: false,
    salesCount: 45,
    ratingAvg: 4.8,
    ratingCount: 15,
    eyebrow: 'Marca e atmosfera',
    accent: 'from-amber-900/30 via-stone-700/20 to-amber-800/15',
    chip: 'bg-amber-900/20 text-amber-100',
    highlights: ['Cafés especiais', 'Doces', 'Brunch'],
    features: ['Cafés', 'Doces', 'Salgados', 'Sanduíches', 'Bebidas'],
    slogan: 'Cafés especiais, doces e brunch com apresentação premium.',
    cor_primaria: '#78350f',
    cor_secundaria: '#a16207',
    preset: TEMPLATE_PRESETS.cafeteria,
    sampleProducts: [
      {
        nome: 'Expresso',
        descricao: 'Café espresso tradicional 50ml.',
        preco: 6.9,
        categoria: 'Cafés',
        ordem: 1,
      },
      {
        nome: 'Cappuccino',
        descricao: 'Espresso, leite vaporizado e espuma.',
        preco: 14.9,
        categoria: 'Cafés',
        ordem: 2,
      },
      {
        nome: 'Latte',
        descricao: 'Espresso com leite vaporizado e arte no leite.',
        preco: 15.9,
        categoria: 'Cafés',
        ordem: 3,
      },
      {
        nome: 'Mocha',
        descricao: 'Espresso, chocolate, leite e chantilly.',
        preco: 18.9,
        categoria: 'Cafés',
        ordem: 4,
      },
      {
        nome: 'Americano',
        descricao: 'Espresso duplo com água quente.',
        preco: 10.9,
        categoria: 'Cafés',
        ordem: 5,
      },
      {
        nome: 'Café com Leite',
        descricao: 'Café coado com leite quente.',
        preco: 8.9,
        categoria: 'Cafés',
        ordem: 6,
      },
      {
        nome: 'Café Gelado',
        descricao: 'Espresso gelado com gelo e leite.',
        preco: 14.9,
        categoria: 'Cafés',
        ordem: 7,
      },
      {
        nome: 'Chá Gelado',
        descricao: 'Chá preto ou verde gelado com limão.',
        preco: 12.9,
        categoria: 'Cafés',
        ordem: 8,
      },
      {
        nome: 'Chocolate Quente',
        descricao: 'Chocolate quente cremoso com chantilly.',
        preco: 16.9,
        categoria: 'Cafés',
        ordem: 9,
      },
      {
        nome: 'Suco Natural 500ml',
        descricao: 'Laranja, limão, maracujá ou abacaxi.',
        preco: 12.9,
        categoria: 'Sucos',
        ordem: 10,
      },
      {
        nome: 'Suco Verde',
        descricao: 'Couve, limão, gengibre e maçã.',
        preco: 14.9,
        categoria: 'Sucos',
        ordem: 11,
      },
      {
        nome: 'Smoothie de Frutas',
        descricao: 'Mistura de frutas com iogurte natural.',
        preco: 16.9,
        categoria: 'Sucos',
        ordem: 12,
      },
      {
        nome: 'Suco de Laranja Natural',
        descricao: 'Laranja espremida na hora.',
        preco: 13.9,
        categoria: 'Sucos',
        ordem: 13,
      },
      {
        nome: 'Vitamina de Banana',
        descricao: 'Banana, leite e aveia.',
        preco: 14.9,
        categoria: 'Sucos',
        ordem: 14,
      },
      {
        nome: 'Croissant de Presunto e Queijo',
        descricao: 'Assado na hora e servido quentinho.',
        preco: 16.9,
        categoria: 'Salgados',
        ordem: 15,
      },
      {
        nome: 'Croissant de Chocolate',
        descricao: 'Croissant recheado com chocolate.',
        preco: 14.9,
        categoria: 'Salgados',
        ordem: 16,
      },
      {
        nome: 'Pão de Queijo',
        descricao: '3 unidades quentinhas.',
        preco: 9.9,
        categoria: 'Salgados',
        ordem: 17,
      },
      {
        nome: 'Misto Quente',
        descricao: 'Pão, presunto e queijo gratinado.',
        preco: 14.9,
        categoria: 'Salgados',
        ordem: 18,
      },
      {
        nome: 'Empada',
        descricao: 'Empada de frango ou palmito.',
        preco: 10.9,
        categoria: 'Salgados',
        ordem: 19,
      },
      {
        nome: 'Esfirra',
        descricao: 'Esfirra de carne, frango ou queijo.',
        preco: 8.9,
        categoria: 'Salgados',
        ordem: 20,
      },
      {
        nome: 'Torta Salgada',
        descricao: 'Fatia de torta de frango ou palmito.',
        preco: 12.9,
        categoria: 'Salgados',
        ordem: 21,
      },
      {
        nome: 'Bolo de Chocolate',
        descricao: 'Fatia generosa com cobertura.',
        preco: 12.9,
        categoria: 'Doces',
        ordem: 22,
      },
      {
        nome: 'Bolo de Cenoura',
        descricao: 'Fatia de bolo de cenoura com cobertura de chocolate.',
        preco: 11.9,
        categoria: 'Doces',
        ordem: 23,
      },
      {
        nome: 'Cheesecake',
        descricao: 'Fatia com frutas vermelhas ou doce de leite.',
        preco: 18.9,
        categoria: 'Doces',
        ordem: 24,
      },
      {
        nome: 'Brownie',
        descricao: 'Brownie de chocolate com nozes.',
        preco: 14.9,
        categoria: 'Doces',
        ordem: 25,
      },
      {
        nome: 'Brigadeiro',
        descricao: '2 unidades de brigadeiro caseiro.',
        preco: 6.9,
        categoria: 'Doces',
        ordem: 26,
      },
      {
        nome: 'Cookie',
        descricao: 'Cookie de chocolate ou aveia e mel.',
        preco: 9.9,
        categoria: 'Doces',
        ordem: 27,
      },
      {
        nome: 'Torta de Limão',
        descricao: 'Fatia de torta de limão com merengue.',
        preco: 14.9,
        categoria: 'Doces',
        ordem: 28,
      },
      {
        nome: 'Pão de Mel',
        descricao: 'Pão de mel caseiro com chocolate.',
        preco: 10.9,
        categoria: 'Doces',
        ordem: 29,
      },
    ],
  },
  acai: {
    slug: 'acai',
    iconKey: 'ice-cream',
    name: 'Açaíteria',
    shortDescription: 'Para açaíterias',
    description:
      'Cardápio para açaíterias e lanchonetes naturais. Com tigelas, copos e adicionais.',
    category: 'acai',
    imageUrl:
      'https://images.unsplash.com/photo-1590080874088-eec64895b423?w=900&auto=format&fit=crop&q=80',
    previewUrl: '/templates/acai',
    priceMonthly: 52,
    priceAnnual: 520,
    price: 52,
    originalPrice: 624,
    isFeatured: false,
    isNew: false,
    isBestseller: false,
    salesCount: 28,
    ratingAvg: 4.5,
    ratingCount: 9,
    eyebrow: 'Visual leve e fresco',
    accent: 'from-fuchsia-600/25 via-purple-600/15 to-violet-700/20',
    chip: 'bg-fuchsia-500/20 text-fuchsia-900',
    highlights: ['Tigelas', 'Complementos', 'Combos fitness'],
    features: ['Açaí no copo', 'Tigelas', 'Adicionais', 'Vitaminas', 'Bebidas'],
    slogan: 'Monte tigelas e complementos sem travar o pedido.',
    cor_primaria: '#7c3aed',
    cor_secundaria: '#a855f7',
    preset: TEMPLATE_PRESETS.acai,
    sampleProducts: [
      {
        nome: 'Açaí 300ml',
        descricao: 'Base cremosa com 2 complementos, 1 calda e 1 fruta.',
        preco: 16.9,
        categoria: 'Copos',
        ordem: 1,
      },
      {
        nome: 'Açaí 500ml',
        descricao: 'Base cremosa com 3 complementos, 1 calda e 1 fruta.',
        preco: 21.9,
        categoria: 'Copos',
        ordem: 2,
      },
      {
        nome: 'Açaí 700ml',
        descricao: 'Base cremosa com 4 complementos, 1 calda e 1 fruta.',
        preco: 26.9,
        categoria: 'Copos',
        ordem: 3,
      },
      {
        nome: 'Tigela 500ml',
        descricao: 'Açaí em camadas com 4 complementos e 1 calda.',
        preco: 24.9,
        categoria: 'Tigelas',
        ordem: 4,
      },
      {
        nome: 'Tigela 1L',
        descricao: 'Porção família com 5 complementos inclusos.',
        preco: 39.9,
        categoria: 'Tigelas',
        ordem: 5,
      },
      {
        nome: 'Tigela Fitness',
        descricao: 'Açaí zero, granola, banana e mel.',
        preco: 26.9,
        categoria: 'Tigelas',
        ordem: 6,
      },
      {
        nome: 'Açaí Napolitano',
        descricao: 'Açaí, morango, banana, granola, leite condensado e Nutella.',
        preco: 28.9,
        categoria: 'Especiais',
        ordem: 7,
      },
      {
        nome: 'Açaí com Paçoca',
        descricao: 'Açaí, banana, granola, leite em pó e paçoca.',
        preco: 24.9,
        categoria: 'Especiais',
        ordem: 8,
      },
      {
        nome: 'Açaí Power',
        descricao: 'Açaí, whey, banana, granola e mel.',
        preco: 29.9,
        categoria: 'Especiais',
        ordem: 9,
      },
      {
        nome: 'Açaí Tropical',
        descricao: 'Açaí, manga, kiwi, granola e leite condensado.',
        preco: 27.9,
        categoria: 'Especiais',
        ordem: 10,
      },
      {
        nome: 'Açaí Zero',
        descricao: 'Açaí sem açúcar, banana e granola.',
        preco: 24.9,
        categoria: 'Especiais',
        ordem: 11,
      },
      {
        nome: 'Copo Casquinha',
        descricao: 'Açaí 400ml com 3 complementos e 1 calda.',
        preco: 19.9,
        categoria: 'Copos',
        ordem: 12,
      },
      {
        nome: 'Adicional Granola',
        descricao: 'Porção extra de granola.',
        preco: 3.9,
        categoria: 'Adicionais',
        ordem: 13,
      },
      {
        nome: 'Adicional Leite Condensado',
        descricao: 'Porção extra de leite condensado.',
        preco: 3.9,
        categoria: 'Adicionais',
        ordem: 14,
      },
      {
        nome: 'Adicional Nutella',
        descricao: 'Porção extra de Nutella.',
        preco: 5.9,
        categoria: 'Adicionais',
        ordem: 15,
      },
      {
        nome: 'Adicional Morango',
        descricao: 'Porção extra de morango fresco.',
        preco: 4.9,
        categoria: 'Adicionais',
        ordem: 16,
      },
      {
        nome: 'Adicional Banana',
        descricao: 'Porção extra de banana.',
        preco: 3.9,
        categoria: 'Adicionais',
        ordem: 17,
      },
      {
        nome: 'Smoothie de Açaí',
        descricao: 'Açaí batido com morango e banana.',
        preco: 15.9,
        categoria: 'Bebidas',
        ordem: 18,
      },
      {
        nome: 'Vitamina de Açaí',
        descricao: 'Açaí batido com leite e banana.',
        preco: 14.9,
        categoria: 'Bebidas',
        ordem: 19,
      },
      {
        nome: 'Suco de Açaí 500ml',
        descricao: 'Açaí batido com guaraná.',
        preco: 12.9,
        categoria: 'Bebidas',
        ordem: 20,
      },
      {
        nome: 'Cupuaçu 500ml',
        descricao: 'Cupuaçu cremoso com complementos.',
        preco: 18.9,
        categoria: 'Bebidas',
        ordem: 21,
      },
      {
        nome: 'Refrigerante 350ml',
        descricao: 'Coca-Cola, Guaraná ou Fanta.',
        preco: 5.9,
        categoria: 'Bebidas',
        ordem: 22,
      },
      {
        nome: 'Água de Coco',
        descricao: 'Água de coco natural 500ml.',
        preco: 9.9,
        categoria: 'Bebidas',
        ordem: 23,
      },
      {
        nome: 'Combo Açaí 500ml + Suco',
        descricao: 'Açaí 500ml + suco de açaí 500ml.',
        preco: 28.9,
        categoria: 'Combos',
        ordem: 24,
      },
      {
        nome: 'Combo Tigela 1L Dupla',
        descricao: 'Duas tigelas de 500ml. Ideal para compartilhar.',
        preco: 44.9,
        categoria: 'Combos',
        ordem: 25,
      },
    ],
  },
  sushi: {
    slug: 'sushi',
    iconKey: 'fish',
    name: 'Japonês / Sushi',
    shortDescription: 'Para restaurantes japoneses',
    description:
      'Cardápio para restaurantes japoneses e sushis. Com sashimis, rolls e temakis.',
    category: 'sushi',
    imageUrl:
      'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=900&auto=format&fit=crop&q=80',
    previewUrl: '/templates/sushi',
    priceMonthly: 74,
    priceAnnual: 740,
    price: 74,
    originalPrice: 888,
    isFeatured: true,
    isNew: false,
    isBestseller: false,
    salesCount: 52,
    ratingAvg: 4.7,
    ratingCount: 18,
    eyebrow: 'Percepção premium',
    accent: 'from-red-900/30 via-rose-900/20 to-stone-900/25',
    chip: 'bg-red-900/25 text-red-100',
    highlights: ['Combinados', 'Temakis', 'Menus premium'],
    features: ['Sushis', 'Sashimis', 'Rolls', 'Temakis', 'Combos'],
    slogan: 'Combinados e peças com visual premium e leitura clara.',
    cor_primaria: '#991b1b',
    cor_secundaria: '#1f2937',
    preset: TEMPLATE_PRESETS.sushi,
    sampleProducts: [
      {
        nome: 'Harumaki',
        descricao: '6 unidades de rolinho primavera frito.',
        preco: 18.9,
        categoria: 'Entradas',
        ordem: 1,
      },
      {
        nome: 'Sunomono',
        descricao: 'Salada de pepino com vinagre de arroz.',
        preco: 14.9,
        categoria: 'Entradas',
        ordem: 2,
      },
      {
        nome: 'Gyoza',
        descricao: '6 unidades de pastel japonês frito ou cozido.',
        preco: 22.9,
        categoria: 'Entradas',
        ordem: 3,
      },
      {
        nome: 'Shimeji na Manteiga',
        descricao: 'Cogumelo shimeji salteado na manteiga.',
        preco: 24.9,
        categoria: 'Entradas',
        ordem: 4,
      },
      {
        nome: 'Sashimi de Salmão',
        descricao: '5 fatias de salmão fresco.',
        preco: 32.9,
        categoria: 'Entradas',
        ordem: 5,
      },
      {
        nome: 'Edamame',
        descricao: 'Vagem de soja cozida com sal.',
        preco: 16.9,
        categoria: 'Entradas',
        ordem: 6,
      },
      {
        nome: 'Combo 12 Peças',
        descricao: 'Seleção de hot rolls, uramaki e niguiris.',
        preco: 39.9,
        categoria: 'Combinados',
        ordem: 7,
      },
      {
        nome: 'Combo 25 Peças',
        descricao: 'Combinado variado com salmão, atum e hot.',
        preco: 59.9,
        categoria: 'Combinados',
        ordem: 8,
      },
      {
        nome: 'Combo Salmão',
        descricao: '15 peças focadas em salmão fresco.',
        preco: 54.9,
        categoria: 'Combinados',
        ordem: 9,
      },
      {
        nome: 'Combo 40 Peças Família',
        descricao: 'Combinado grande para 3-4 pessoas.',
        preco: 89.9,
        categoria: 'Combinados',
        ordem: 10,
      },
      {
        nome: 'Combo Premium',
        descricao: 'Sashimi, niguiri e rolls especiais. 20 peças.',
        preco: 74.9,
        categoria: 'Combinados',
        ordem: 11,
      },
      {
        nome: 'Temaki Salmão',
        descricao: 'Salmão fresco, arroz e nori.',
        preco: 22.9,
        categoria: 'Temakis',
        ordem: 12,
      },
      {
        nome: 'Temaki Califórnia',
        descricao: 'Kani, pepino, manga e cream cheese.',
        preco: 19.9,
        categoria: 'Temakis',
        ordem: 13,
      },
      {
        nome: 'Temaki Atum',
        descricao: 'Atum fresco, arroz e nori.',
        preco: 24.9,
        categoria: 'Temakis',
        ordem: 14,
      },
      {
        nome: 'Temaki Camarão',
        descricao: 'Camarão empanado, pepino e maionese.',
        preco: 24.9,
        categoria: 'Temakis',
        ordem: 15,
      },
      {
        nome: 'Temaki Skin',
        descricao: 'Pele de salmão crocante, pepino e cream cheese.',
        preco: 21.9,
        categoria: 'Temakis',
        ordem: 16,
      },
      {
        nome: 'Hot Philadelphia',
        descricao: 'Salmão, cream cheese empanado e frito.',
        preco: 28.9,
        categoria: 'Rolls',
        ordem: 17,
      },
      {
        nome: 'Uramaki Skin',
        descricao: 'Pele de salmão crocante, pepino e maionese.',
        preco: 26.9,
        categoria: 'Rolls',
        ordem: 18,
      },
      {
        nome: 'Philadelphia Roll',
        descricao: 'Salmão, cream cheese e pepino.',
        preco: 24.9,
        categoria: 'Rolls',
        ordem: 19,
      },
      {
        nome: 'California Roll',
        descricao: 'Kani, pepino, manga e cream cheese.',
        preco: 22.9,
        categoria: 'Rolls',
        ordem: 20,
      },
      {
        nome: 'Dragon Roll',
        descricao: 'Salmão, pepino e abacate com molho especial.',
        preco: 32.9,
        categoria: 'Rolls',
        ordem: 21,
      },
      {
        nome: 'Rainbow Roll',
        descricao: 'California com fatias de peixe variados.',
        preco: 34.9,
        categoria: 'Rolls',
        ordem: 22,
      },
      {
        nome: 'Niguiri Salmão',
        descricao: '2 unidades de niguiri de salmão.',
        preco: 18.9,
        categoria: 'Rolls',
        ordem: 23,
      },
      {
        nome: 'Niguiri Atum',
        descricao: '2 unidades de niguiri de atum.',
        preco: 19.9,
        categoria: 'Rolls',
        ordem: 24,
      },
      {
        nome: 'Yakissoba',
        descricao: 'Macarrão frito com legumes e proteína.',
        preco: 34.9,
        categoria: 'Pratos quentes',
        ordem: 25,
      },
      {
        nome: 'Lámen',
        descricao: 'Macarrão em caldo com chashu, ovo e nori.',
        preco: 42.9,
        categoria: 'Pratos quentes',
        ordem: 26,
      },
      {
        nome: 'Tempurá',
        descricao: 'Camarões e legumes empanados e fritos.',
        preco: 38.9,
        categoria: 'Pratos quentes',
        ordem: 27,
      },
      {
        nome: 'Lámen Picante',
        descricao: 'Lámen com caldo picante e chashu.',
        preco: 44.9,
        categoria: 'Pratos quentes',
        ordem: 28,
      },
      {
        nome: 'Yakimeshi',
        descricao: 'Arroz frito japonês com legumes e ovo.',
        preco: 28.9,
        categoria: 'Pratos quentes',
        ordem: 29,
      },
      {
        nome: 'Refrigerante 350ml',
        descricao: 'Coca-Cola, Guaraná ou água.',
        preco: 6.9,
        categoria: 'Bebidas',
        ordem: 30,
      },
      {
        nome: 'Chá Gelado',
        descricao: 'Chá verde ou chá de pêssego gelado.',
        preco: 8.9,
        categoria: 'Bebidas',
        ordem: 31,
      },
      {
        nome: 'Sake',
        descricao: 'Dose de sake japonês.',
        preco: 24.9,
        categoria: 'Bebidas',
        ordem: 32,
      },
    ],
  },
}

export const RESTAURANT_TEMPLATES = Object.values(RESTAURANT_TEMPLATE_CONFIGS)

export function getRestaurantTemplateConfig(slug?: string | null) {
  const normalized = typeof slug === 'string' ? slug.trim().toLowerCase() : ''
  if (!normalized) {
    return RESTAURANT_TEMPLATE_CONFIGS.restaurante
  }

  const config = RESTAURANT_TEMPLATE_CONFIGS[normalized as RestaurantTemplateSlug]
  return config || RESTAURANT_TEMPLATE_CONFIGS.restaurante
}

export function getTemplateCatalog(): Template[] {
  return RESTAURANT_TEMPLATES.map((template) => ({
    id: template.slug,
    slug: template.slug,
    name: template.name,
    description: template.description,
    shortDescription: template.shortDescription,
    price: template.priceMonthly,
    originalPrice: template.originalPrice,
    priceMonthly: template.priceMonthly,
    priceAnnual: template.priceAnnual,
    category: template.category,
    imageUrl: template.imageUrl,
    previewUrl: template.previewUrl,
    features: template.features,
    isFeatured: template.isFeatured,
    isNew: template.isNew,
    isBestseller: template.isBestseller,
    salesCount: template.salesCount,
    ratingAvg: template.ratingAvg,
    ratingCount: template.ratingCount,
    status: 'active',
  }))
}

export function buildTemplateDemoData(slug: RestaurantTemplateSlug) {
  const template = getRestaurantTemplateConfig(slug)

  return {
    restaurant: {
      id: `demo-${template.slug}`,
      user_id: 'demo-user',
      nome: `${template.name} Demo`,
      slug: `demo-${template.slug}`,
      telefone: '11999999999',
      logo_url: null,
      banner_url: template.imageUrl,
      slogan: template.slogan,
      cor_primaria: '#d97706',
      cor_secundaria: '#ea580c',
      template_slug: template.slug,
      google_maps_url: 'https://www.google.com/maps?q=Av.+Paulista,+1578,+Bela+Vista,+São+Paulo',
      endereco_texto: 'Av. Paulista, 1578 - Bela Vista, São Paulo - SP',
      customizacao: null,
      ativo: true,
    },
    products: template.sampleProducts.map((product, index) => ({
      id: `demo-${template.slug}-${index + 1}`,
      restaurant_id: `demo-${template.slug}`,
      nome: product.nome,
      descricao: product.descricao,
      preco: product.preco,
      imagem_url: product.imagem_url || template.imageUrl,
      categoria: product.categoria,
      ativo: true,
      ordem: product.ordem,
    })),
  }
}